# accent era yok
# Site settings
# in the templates available like {{ site.myvariable }}.
title: Clean portfolio theme for Jekyll powered by Bootstrap 4.
email: your-email@domain.com
brand: Anasayfa
headline: Hızlı, Kolay ve Pratik
description: > Açıklama
deneme
denememe # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "demirkesenotokiralama" # the subpath of your site, e.g. /blog
url: "https://borfirbora.com" # the base hostname & protocol for your site
copyright: 2019 Demirkesen Oto Kiralama, Tüm Hakları Saklıdır

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: demirkesenotokiralama@gmail.com
phone: +90 (534) 226 26 29

# Tracking
googleAnalitycsID: UA-83933844-1


collections:
  kampanya:
    output: true
    permalink: /kampanya/:name
  araba:
    output: true
    permalink: /araba/:name