# accent era yok
# Site settings
# in the templates available like {{ site.myvariable }}.
title: Demirkesen Oto Kiralama
email: demirkesenotokiralama@gmail.com
brand: Anasayfa
headline: Hızlı, Kolay ve Pratik
description: >
  Açıklama
  deneme
  denememe # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "/demirkesenotokiralama" # the subpath of your site, e.g. /blog
url: "https://borfirbora.com" # the base hostname & protocol for your site
copyright: 2019 Demirkesen Oto Kiralama, Tüm Hakları Saklıdır

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: demirkesenotokiralama@gmail.com
phone: +90 (534) 226 26 29

# Tracking
googleAnalitycsID: UA-83933844-1



collections:
  kampanya:
    output: true
    permalink: /kampanya/:title
  araba:
    output: true
    permalink: /araba/:title


prose:
  rooturl: ''
  media: 'araba'
  ignore:
    - 404.html
    - LICENSE
    - feed.xml
    - _config.yml
    - /_layouts
    - /_includes
    - /css
    - /_web_src
    - /web-dist
    - /img
    - /js
  metadata:
    _araba:
      - name: "layout"
        field:
          element: "hidden"
          value: "araba"
      - name: "title"
        field:
          element: "text"
          label: "Araba'nın Markası"
          placeholder: "Reno Clio"
          alterable: true
      - name: "koltuk"
        field:
          element: "text"
          label: "Koltuk Sayısı"
          placeholder: "4"
          alterable: true
      - name: "yakit"
        field:
          element: "text"
          label: "Aracın Yakıt Türü"
          placeholder: "Dizel"
          alterable: true
      - name: "resim"
        field:
          element: "text"
          label: "Resim"
          help: "Arabanın Resmi için dosya adı"
          placeholder: "araba/reno.jpg"
          alterable: true
      - name: "gunluk"
        field:
          element: "text"
          label: "Aracın Günlük Kira Bedeli"
          alterable: true
      - name: "aylik"
        field:
          element: "text"
          label: "Aracın Aylık Kira Bedeli"
          alterable: true
    _kampanya:
      - name: "layout"
        field:
          element: "hidden"
          value: "kampanya"
      - name: "title"
        field:
          element: "text"
          label: "Kampanya Başlığı"
          placeholder: "Reno'lara özel 15 günlük sadece 900 lira"
          alterable: true
      - name: "baslangic"
        field:
          element: "text"
          label: "Başlangıç tarihi"
          placeholder: "21.12.2019"
          alterable: true
      - name: "bitis"
        field:
          element: "text"
          label: "Bitiş Tarihi"
          placeholder: "21.12.2019"
          alterable: true
      - name: "resim"
        field:
          element: "text"
          label: "Kampanya Görseli"
          help: "Kampanyanın Resmi için dosya adı"
          placeholder: "araba/reno.jpg"
          alterable: true
